//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Data.Objects;
using System.Data.Objects.DataClasses;
using System.Data.EntityClient;
using System.ComponentModel;
using System.Xml.Serialization;
using System.Runtime.Serialization;

[assembly: EdmSchemaAttribute()]
#region EDM Relationship Metadata

[assembly: EdmRelationshipAttribute("ItemCoreModel", "ItemCategory", "Category", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(ItemSoft.Data.Category), "Item", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(ItemSoft.Data.Item))]

#endregion

namespace ItemSoft.Data
{
    #region Contexts
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    public partial class ItemCoreEntities : ObjectContext
    {
        #region Constructors
    
        /// <summary>
        /// Initializes a new ItemCoreEntities object using the connection string found in the 'ItemCoreEntities' section of the application configuration file.
        /// </summary>
        public ItemCoreEntities() : base("name=ItemCoreEntities", "ItemCoreEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new ItemCoreEntities object.
        /// </summary>
        public ItemCoreEntities(string connectionString) : base(connectionString, "ItemCoreEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new ItemCoreEntities object.
        /// </summary>
        public ItemCoreEntities(EntityConnection connection) : base(connection, "ItemCoreEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        #endregion
    
        #region Partial Methods
    
        partial void OnContextCreated();
    
        #endregion
    
        #region ObjectSet Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<Category> Category
        {
            get
            {
                if ((_Category == null))
                {
                    _Category = base.CreateObjectSet<Category>("Category");
                }
                return _Category;
            }
        }
        private ObjectSet<Category> _Category;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<Item> Item
        {
            get
            {
                if ((_Item == null))
                {
                    _Item = base.CreateObjectSet<Item>("Item");
                }
                return _Item;
            }
        }
        private ObjectSet<Item> _Item;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<Pricing> Pricing
        {
            get
            {
                if ((_Pricing == null))
                {
                    _Pricing = base.CreateObjectSet<Pricing>("Pricing");
                }
                return _Pricing;
            }
        }
        private ObjectSet<Pricing> _Pricing;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<Setting> Setting
        {
            get
            {
                if ((_Setting == null))
                {
                    _Setting = base.CreateObjectSet<Setting>("Setting");
                }
                return _Setting;
            }
        }
        private ObjectSet<Setting> _Setting;

        #endregion
        #region AddTo Methods
    
        /// <summary>
        /// Deprecated Method for adding a new object to the Category EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToCategory(Category category)
        {
            base.AddObject("Category", category);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the Item EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToItem(Item item)
        {
            base.AddObject("Item", item);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the Pricing EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToPricing(Pricing pricing)
        {
            base.AddObject("Pricing", pricing);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the Setting EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToSetting(Setting setting)
        {
            base.AddObject("Setting", setting);
        }

        #endregion
    }
    

    #endregion
    
    #region Entities
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="ItemCoreModel", Name="Category")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class Category : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new Category object.
        /// </summary>
        /// <param name="categoryId">Initial value of the CategoryId property.</param>
        public static Category CreateCategory(global::System.Int32 categoryId)
        {
            Category category = new Category();
            category.CategoryId = categoryId;
            return category;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 CategoryId
        {
            get
            {
                return _CategoryId;
            }
            set
            {
                if (_CategoryId != value)
                {
                    OnCategoryIdChanging(value);
                    ReportPropertyChanging("CategoryId");
                    _CategoryId = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("CategoryId");
                    OnCategoryIdChanged();
                }
            }
        }
        private global::System.Int32 _CategoryId;
        partial void OnCategoryIdChanging(global::System.Int32 value);
        partial void OnCategoryIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Name
        {
            get
            {
                return _Name;
            }
            set
            {
                OnNameChanging(value);
                ReportPropertyChanging("Name");
                _Name = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Name");
                OnNameChanged();
            }
        }
        private global::System.String _Name;
        partial void OnNameChanging(global::System.String value);
        partial void OnNameChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> ParentId
        {
            get
            {
                return _ParentId;
            }
            set
            {
                OnParentIdChanging(value);
                ReportPropertyChanging("ParentId");
                _ParentId = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("ParentId");
                OnParentIdChanged();
            }
        }
        private Nullable<global::System.Int32> _ParentId;
        partial void OnParentIdChanging(Nullable<global::System.Int32> value);
        partial void OnParentIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String ImagePath
        {
            get
            {
                return _ImagePath;
            }
            set
            {
                OnImagePathChanging(value);
                ReportPropertyChanging("ImagePath");
                _ImagePath = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("ImagePath");
                OnImagePathChanged();
            }
        }
        private global::System.String _ImagePath;
        partial void OnImagePathChanging(global::System.String value);
        partial void OnImagePathChanged();

        #endregion
    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("ItemCoreModel", "ItemCategory", "Item")]
        public EntityCollection<Item> Item
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<Item>("ItemCoreModel.ItemCategory", "Item");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<Item>("ItemCoreModel.ItemCategory", "Item", value);
                }
            }
        }

        #endregion
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="ItemCoreModel", Name="Item")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class Item : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new Item object.
        /// </summary>
        /// <param name="itemId">Initial value of the ItemId property.</param>
        public static Item CreateItem(global::System.Int32 itemId)
        {
            Item item = new Item();
            item.ItemId = itemId;
            return item;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 ItemId
        {
            get
            {
                return _ItemId;
            }
            set
            {
                if (_ItemId != value)
                {
                    OnItemIdChanging(value);
                    ReportPropertyChanging("ItemId");
                    _ItemId = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("ItemId");
                    OnItemIdChanged();
                }
            }
        }
        private global::System.Int32 _ItemId;
        partial void OnItemIdChanging(global::System.Int32 value);
        partial void OnItemIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Zupid
        {
            get
            {
                return _Zupid;
            }
            set
            {
                OnZupidChanging(value);
                ReportPropertyChanging("Zupid");
                _Zupid = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Zupid");
                OnZupidChanged();
            }
        }
        private global::System.String _Zupid;
        partial void OnZupidChanging(global::System.String value);
        partial void OnZupidChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String MerchantProductNumber
        {
            get
            {
                return _MerchantProductNumber;
            }
            set
            {
                OnMerchantProductNumberChanging(value);
                ReportPropertyChanging("MerchantProductNumber");
                _MerchantProductNumber = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("MerchantProductNumber");
                OnMerchantProductNumberChanged();
            }
        }
        private global::System.String _MerchantProductNumber;
        partial void OnMerchantProductNumberChanging(global::System.String value);
        partial void OnMerchantProductNumberChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String ProductName
        {
            get
            {
                return _ProductName;
            }
            set
            {
                OnProductNameChanging(value);
                ReportPropertyChanging("ProductName");
                _ProductName = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("ProductName");
                OnProductNameChanged();
            }
        }
        private global::System.String _ProductName;
        partial void OnProductNameChanging(global::System.String value);
        partial void OnProductNameChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String ProductPrice
        {
            get
            {
                return _ProductPrice;
            }
            set
            {
                OnProductPriceChanging(value);
                ReportPropertyChanging("ProductPrice");
                _ProductPrice = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("ProductPrice");
                OnProductPriceChanged();
            }
        }
        private global::System.String _ProductPrice;
        partial void OnProductPriceChanging(global::System.String value);
        partial void OnProductPriceChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String CurrencySymbolOfPrice
        {
            get
            {
                return _CurrencySymbolOfPrice;
            }
            set
            {
                OnCurrencySymbolOfPriceChanging(value);
                ReportPropertyChanging("CurrencySymbolOfPrice");
                _CurrencySymbolOfPrice = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("CurrencySymbolOfPrice");
                OnCurrencySymbolOfPriceChanged();
            }
        }
        private global::System.String _CurrencySymbolOfPrice;
        partial void OnCurrencySymbolOfPriceChanging(global::System.String value);
        partial void OnCurrencySymbolOfPriceChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String ValidFromDatre
        {
            get
            {
                return _ValidFromDatre;
            }
            set
            {
                OnValidFromDatreChanging(value);
                ReportPropertyChanging("ValidFromDatre");
                _ValidFromDatre = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("ValidFromDatre");
                OnValidFromDatreChanged();
            }
        }
        private global::System.String _ValidFromDatre;
        partial void OnValidFromDatreChanging(global::System.String value);
        partial void OnValidFromDatreChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String ValidToDate
        {
            get
            {
                return _ValidToDate;
            }
            set
            {
                OnValidToDateChanging(value);
                ReportPropertyChanging("ValidToDate");
                _ValidToDate = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("ValidToDate");
                OnValidToDateChanged();
            }
        }
        private global::System.String _ValidToDate;
        partial void OnValidToDateChanging(global::System.String value);
        partial void OnValidToDateChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String ProductShortDescription
        {
            get
            {
                return _ProductShortDescription;
            }
            set
            {
                OnProductShortDescriptionChanging(value);
                ReportPropertyChanging("ProductShortDescription");
                _ProductShortDescription = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("ProductShortDescription");
                OnProductShortDescriptionChanged();
            }
        }
        private global::System.String _ProductShortDescription;
        partial void OnProductShortDescriptionChanging(global::System.String value);
        partial void OnProductShortDescriptionChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String ProductLongDescription
        {
            get
            {
                return _ProductLongDescription;
            }
            set
            {
                OnProductLongDescriptionChanging(value);
                ReportPropertyChanging("ProductLongDescription");
                _ProductLongDescription = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("ProductLongDescription");
                OnProductLongDescriptionChanged();
            }
        }
        private global::System.String _ProductLongDescription;
        partial void OnProductLongDescriptionChanging(global::System.String value);
        partial void OnProductLongDescriptionChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String MerhantProductCategory
        {
            get
            {
                return _MerhantProductCategory;
            }
            set
            {
                OnMerhantProductCategoryChanging(value);
                ReportPropertyChanging("MerhantProductCategory");
                _MerhantProductCategory = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("MerhantProductCategory");
                OnMerhantProductCategoryChanged();
            }
        }
        private global::System.String _MerhantProductCategory;
        partial void OnMerhantProductCategoryChanging(global::System.String value);
        partial void OnMerhantProductCategoryChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String ZanoxCategoryIds
        {
            get
            {
                return _ZanoxCategoryIds;
            }
            set
            {
                OnZanoxCategoryIdsChanging(value);
                ReportPropertyChanging("ZanoxCategoryIds");
                _ZanoxCategoryIds = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("ZanoxCategoryIds");
                OnZanoxCategoryIdsChanged();
            }
        }
        private global::System.String _ZanoxCategoryIds;
        partial void OnZanoxCategoryIdsChanging(global::System.String value);
        partial void OnZanoxCategoryIdsChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String ImageSmallUrl
        {
            get
            {
                return _ImageSmallUrl;
            }
            set
            {
                OnImageSmallUrlChanging(value);
                ReportPropertyChanging("ImageSmallUrl");
                _ImageSmallUrl = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("ImageSmallUrl");
                OnImageSmallUrlChanged();
            }
        }
        private global::System.String _ImageSmallUrl;
        partial void OnImageSmallUrlChanging(global::System.String value);
        partial void OnImageSmallUrlChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String ImageMediumUrl
        {
            get
            {
                return _ImageMediumUrl;
            }
            set
            {
                OnImageMediumUrlChanging(value);
                ReportPropertyChanging("ImageMediumUrl");
                _ImageMediumUrl = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("ImageMediumUrl");
                OnImageMediumUrlChanged();
            }
        }
        private global::System.String _ImageMediumUrl;
        partial void OnImageMediumUrlChanging(global::System.String value);
        partial void OnImageMediumUrlChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String ImageLargeUrl
        {
            get
            {
                return _ImageLargeUrl;
            }
            set
            {
                OnImageLargeUrlChanging(value);
                ReportPropertyChanging("ImageLargeUrl");
                _ImageLargeUrl = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("ImageLargeUrl");
                OnImageLargeUrlChanged();
            }
        }
        private global::System.String _ImageLargeUrl;
        partial void OnImageLargeUrlChanging(global::System.String value);
        partial void OnImageLargeUrlChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String ProductManufacturerBran
        {
            get
            {
                return _ProductManufacturerBran;
            }
            set
            {
                OnProductManufacturerBranChanging(value);
                ReportPropertyChanging("ProductManufacturerBran");
                _ProductManufacturerBran = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("ProductManufacturerBran");
                OnProductManufacturerBranChanged();
            }
        }
        private global::System.String _ProductManufacturerBran;
        partial void OnProductManufacturerBranChanging(global::System.String value);
        partial void OnProductManufacturerBranChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String ZanoxProductLink
        {
            get
            {
                return _ZanoxProductLink;
            }
            set
            {
                OnZanoxProductLinkChanging(value);
                ReportPropertyChanging("ZanoxProductLink");
                _ZanoxProductLink = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("ZanoxProductLink");
                OnZanoxProductLinkChanged();
            }
        }
        private global::System.String _ZanoxProductLink;
        partial void OnZanoxProductLinkChanging(global::System.String value);
        partial void OnZanoxProductLinkChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String MerchantProductCategoryNumber
        {
            get
            {
                return _MerchantProductCategoryNumber;
            }
            set
            {
                OnMerchantProductCategoryNumberChanging(value);
                ReportPropertyChanging("MerchantProductCategoryNumber");
                _MerchantProductCategoryNumber = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("MerchantProductCategoryNumber");
                OnMerchantProductCategoryNumberChanged();
            }
        }
        private global::System.String _MerchantProductCategoryNumber;
        partial void OnMerchantProductCategoryNumberChanging(global::System.String value);
        partial void OnMerchantProductCategoryNumberChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String DeliveryTime
        {
            get
            {
                return _DeliveryTime;
            }
            set
            {
                OnDeliveryTimeChanging(value);
                ReportPropertyChanging("DeliveryTime");
                _DeliveryTime = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("DeliveryTime");
                OnDeliveryTimeChanged();
            }
        }
        private global::System.String _DeliveryTime;
        partial void OnDeliveryTimeChanging(global::System.String value);
        partial void OnDeliveryTimeChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String TermsOfContract
        {
            get
            {
                return _TermsOfContract;
            }
            set
            {
                OnTermsOfContractChanging(value);
                ReportPropertyChanging("TermsOfContract");
                _TermsOfContract = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("TermsOfContract");
                OnTermsOfContractChanged();
            }
        }
        private global::System.String _TermsOfContract;
        partial void OnTermsOfContractChanging(global::System.String value);
        partial void OnTermsOfContractChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String ProductEAN
        {
            get
            {
                return _ProductEAN;
            }
            set
            {
                OnProductEANChanging(value);
                ReportPropertyChanging("ProductEAN");
                _ProductEAN = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("ProductEAN");
                OnProductEANChanged();
            }
        }
        private global::System.String _ProductEAN;
        partial void OnProductEANChanging(global::System.String value);
        partial void OnProductEANChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String ISBN
        {
            get
            {
                return _ISBN;
            }
            set
            {
                OnISBNChanging(value);
                ReportPropertyChanging("ISBN");
                _ISBN = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("ISBN");
                OnISBNChanged();
            }
        }
        private global::System.String _ISBN;
        partial void OnISBNChanging(global::System.String value);
        partial void OnISBNChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String ShippingAndHandling
        {
            get
            {
                return _ShippingAndHandling;
            }
            set
            {
                OnShippingAndHandlingChanging(value);
                ReportPropertyChanging("ShippingAndHandling");
                _ShippingAndHandling = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("ShippingAndHandling");
                OnShippingAndHandlingChanged();
            }
        }
        private global::System.String _ShippingAndHandling;
        partial void OnShippingAndHandlingChanging(global::System.String value);
        partial void OnShippingAndHandlingChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String ShippingAndHandlingCost
        {
            get
            {
                return _ShippingAndHandlingCost;
            }
            set
            {
                OnShippingAndHandlingCostChanging(value);
                ReportPropertyChanging("ShippingAndHandlingCost");
                _ShippingAndHandlingCost = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("ShippingAndHandlingCost");
                OnShippingAndHandlingCostChanged();
            }
        }
        private global::System.String _ShippingAndHandlingCost;
        partial void OnShippingAndHandlingCostChanging(global::System.String value);
        partial void OnShippingAndHandlingCostChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String ExtraTextOne
        {
            get
            {
                return _ExtraTextOne;
            }
            set
            {
                OnExtraTextOneChanging(value);
                ReportPropertyChanging("ExtraTextOne");
                _ExtraTextOne = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("ExtraTextOne");
                OnExtraTextOneChanged();
            }
        }
        private global::System.String _ExtraTextOne;
        partial void OnExtraTextOneChanging(global::System.String value);
        partial void OnExtraTextOneChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String ExtraTextTwo
        {
            get
            {
                return _ExtraTextTwo;
            }
            set
            {
                OnExtraTextTwoChanging(value);
                ReportPropertyChanging("ExtraTextTwo");
                _ExtraTextTwo = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("ExtraTextTwo");
                OnExtraTextTwoChanged();
            }
        }
        private global::System.String _ExtraTextTwo;
        partial void OnExtraTextTwoChanging(global::System.String value);
        partial void OnExtraTextTwoChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String ExtraTextTree
        {
            get
            {
                return _ExtraTextTree;
            }
            set
            {
                OnExtraTextTreeChanging(value);
                ReportPropertyChanging("ExtraTextTree");
                _ExtraTextTree = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("ExtraTextTree");
                OnExtraTextTreeChanged();
            }
        }
        private global::System.String _ExtraTextTree;
        partial void OnExtraTextTreeChanging(global::System.String value);
        partial void OnExtraTextTreeChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Culture
        {
            get
            {
                return _Culture;
            }
            set
            {
                OnCultureChanging(value);
                ReportPropertyChanging("Culture");
                _Culture = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Culture");
                OnCultureChanged();
            }
        }
        private global::System.String _Culture;
        partial void OnCultureChanging(global::System.String value);
        partial void OnCultureChanged();

        #endregion
    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("ItemCoreModel", "ItemCategory", "Category")]
        public EntityCollection<Category> Category
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<Category>("ItemCoreModel.ItemCategory", "Category");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<Category>("ItemCoreModel.ItemCategory", "Category", value);
                }
            }
        }

        #endregion
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="ItemCoreModel", Name="Pricing")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class Pricing : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new Pricing object.
        /// </summary>
        /// <param name="pricingId">Initial value of the PricingId property.</param>
        public static Pricing CreatePricing(global::System.Int32 pricingId)
        {
            Pricing pricing = new Pricing();
            pricing.PricingId = pricingId;
            return pricing;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 PricingId
        {
            get
            {
                return _PricingId;
            }
            set
            {
                if (_PricingId != value)
                {
                    OnPricingIdChanging(value);
                    ReportPropertyChanging("PricingId");
                    _PricingId = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("PricingId");
                    OnPricingIdChanged();
                }
            }
        }
        private global::System.Int32 _PricingId;
        partial void OnPricingIdChanging(global::System.Int32 value);
        partial void OnPricingIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Name
        {
            get
            {
                return _Name;
            }
            set
            {
                OnNameChanging(value);
                ReportPropertyChanging("Name");
                _Name = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Name");
                OnNameChanged();
            }
        }
        private global::System.String _Name;
        partial void OnNameChanging(global::System.String value);
        partial void OnNameChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Path
        {
            get
            {
                return _Path;
            }
            set
            {
                OnPathChanging(value);
                ReportPropertyChanging("Path");
                _Path = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Path");
                OnPathChanged();
            }
        }
        private global::System.String _Path;
        partial void OnPathChanging(global::System.String value);
        partial void OnPathChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Culture
        {
            get
            {
                return _Culture;
            }
            set
            {
                OnCultureChanging(value);
                ReportPropertyChanging("Culture");
                _Culture = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Culture");
                OnCultureChanged();
            }
        }
        private global::System.String _Culture;
        partial void OnCultureChanging(global::System.String value);
        partial void OnCultureChanged();

        #endregion
    
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="ItemCoreModel", Name="Setting")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class Setting : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new Setting object.
        /// </summary>
        /// <param name="settingId">Initial value of the SettingId property.</param>
        public static Setting CreateSetting(global::System.Int32 settingId)
        {
            Setting setting = new Setting();
            setting.SettingId = settingId;
            return setting;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 SettingId
        {
            get
            {
                return _SettingId;
            }
            set
            {
                if (_SettingId != value)
                {
                    OnSettingIdChanging(value);
                    ReportPropertyChanging("SettingId");
                    _SettingId = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("SettingId");
                    OnSettingIdChanged();
                }
            }
        }
        private global::System.Int32 _SettingId;
        partial void OnSettingIdChanging(global::System.Int32 value);
        partial void OnSettingIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Name
        {
            get
            {
                return _Name;
            }
            set
            {
                OnNameChanging(value);
                ReportPropertyChanging("Name");
                _Name = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Name");
                OnNameChanged();
            }
        }
        private global::System.String _Name;
        partial void OnNameChanging(global::System.String value);
        partial void OnNameChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Value
        {
            get
            {
                return _Value;
            }
            set
            {
                OnValueChanging(value);
                ReportPropertyChanging("Value");
                _Value = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Value");
                OnValueChanged();
            }
        }
        private global::System.String _Value;
        partial void OnValueChanging(global::System.String value);
        partial void OnValueChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Description
        {
            get
            {
                return _Description;
            }
            set
            {
                OnDescriptionChanging(value);
                ReportPropertyChanging("Description");
                _Description = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Description");
                OnDescriptionChanged();
            }
        }
        private global::System.String _Description;
        partial void OnDescriptionChanging(global::System.String value);
        partial void OnDescriptionChanged();

        #endregion
    
    }

    #endregion
    
}
